version: 2

conda:
  environment: docs/environment.yml

build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-4.10"

sphinx:
  fail_on_warning: false

python:
  install:
    - method: pip
      path: .

formats:
  - pdf
  - epub
