channels:
  - conda-forge

dependencies:
  - pip=22.3.1
  - python=3.10.8
  - numpy=1.23.3
  - sphinx=5.3.0
  - sphinx-autoapi=2.0.0
  - pygit2=1.10.1
  - attrs=21.4.0
  - numpy=1.23.3
  - scipy=1.9.3
  - networkx=2.8.8
  - rich=12.6.0
  - pip:
    - mcpid ==0.0.4
    - typicle ==0.1.4
    - pyjet ==1.9.0
    - sphinx_mdinclude ==0.5.3
    - sphinx-immaterial ==0.10.0
