name: tests

on:
  - push

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        pyver: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: '1.3.1-0'
          environment-name: test-env
          create-args: >-
            python=${{ matrix.pyver }}
            pytest>=6.2.5
          init-shell: bash
          cache-environment: true
          post-cleanup: 'all'

      - name: Install graphicle
        shell: bash -el {0}
        run: pip install .

      - name: Run tests
        shell: bash -el {0}
        run: pytest
